version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 806627825545.dkr.ecr.us-east-1.amazonaws.com
    
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ecs-new .
      - docker tag ecs-new:latest 806627825545.dkr.ecr.us-east-1.amazonaws.com/ecs-new:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 806627825545.dkr.ecr.us-east-1.amazonaws.com/ecs-new:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$IMAGE_REPO_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
